#ifndef TRANSDUCERLOGIC_GLOBAL_H
#define TRANSDUCERLOGIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSDUCERLOGIC_LIBRARY)
#  define TRANSDUCERLOGICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANSDUCERLOGICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSDUCERLOGIC_GLOBAL_H
